### ISSUE TITLE
run outstation.py，but loop connect itself!

### ISSUE THREAD

**Issue by Feng11Q** [Kisensum/pydnp3#19]
please help me,

I run the code from ‘https://github.com/ChargePoint/pydnp3/blob/master/examples/outstation.py’

but Loop receives the following message:
server - Accepted connection from: 192.xx.xx.xx(ip of the outstation)
![image](https://user-images.githubusercontent.com/32813467/72491074-e72abc00-3853-11ea-89e1-b1f945028943.png)

How should I run an outstation correctly?

**Comment by fqlq** [comment]
我发现是因为后台启动了很多master_cmd.py，但是我并没有启动，是否是core dump后后台程序被保留了？
